Repository AY2021S2-CS2103-W16-2/tp, pull requests merged in 2021-03, with the labels that each got.

#23 Storage management
  src/main/java/seedu/address/model/AbstractDate.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/main/java/seedu/address/model/cheese/UniqueCheeseList.java
  src/main/java/seedu/address/model/cheese/exceptions/CheeseNotFoundException.java
  src/main/java/seedu/address/model/cheese/exceptions/DuplicateCheeseException.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/storage/JsonAdaptedCheese.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidCustomerAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalCheese.java
  src/test/java/seedu/address/testutil/TypicalCustomers.java
  src/test/java/seedu/address/testutil/TypicalModels.java
  src/test/java/seedu/address/testutil/TypicalOrder.java
Labels: enhancement

#20 Feat/List Commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCheesesCommand.java
  src/main/java/seedu/address/logic/commands/ListCustomersCommand.java
  src/main/java/seedu/address/logic/commands/ListOrdersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AbstractDate.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCheese.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/cards/CheeseCard.java
  src/main/java/seedu/address/ui/cards/CustomerCard.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/java/seedu/address/ui/panels/CheeseListPanel.java
  src/main/java/seedu/address/ui/panels/CustomerListPanel.java
  src/main/java/seedu/address/ui/panels/OrderListPanel.java
  src/main/resources/view/CheeseCard.fxml
  src/main/resources/view/CustomerCard.fxml
  src/main/resources/view/ListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/OrderCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCheesesCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCustomersCommandTest.java
  src/test/java/seedu/address/logic/commands/ListOrdersCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
Labels: enhancement

#30 Add Done command for order
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/main/java/seedu/address/model/cheese/UniqueCheeseList.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/OrderContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/order/Quantity.java
  src/main/java/seedu/address/storage/JsonAdaptedCheese.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/testutil/CheeseBuilder.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalCheese.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalOrder.java
Labels: enhancement

#32 Add AddCommands Parsing and Execution
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCheeseCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddCheeseCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/AddOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AbstractDate.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/main/java/seedu/address/model/cheese/CheeseId.java
  src/main/java/seedu/address/model/cheese/ManufactureDate.java
  src/main/java/seedu/address/model/customer/CustomerId.java
  src/main/java/seedu/address/model/customer/UniqueCustomerList.java
  src/main/java/seedu/address/model/order/OrderDate.java
  src/main/java/seedu/address/model/order/OrderId.java
  src/main/java/seedu/address/storage/JsonAdaptedCheese.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/ui/cards/CheeseCard.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddCheeseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddCustomerCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/CheeseIdStub.java
  src/test/java/seedu/address/model/OrderIdStub.java
  src/test/java/seedu/address/model/cheese/CheeseIdTest.java
  src/test/java/seedu/address/model/order/OrderIdTest.java
  src/test/java/seedu/address/testutil/CheeseBuilder.java
  src/test/java/seedu/address/testutil/CheeseUtil.java
  src/test/java/seedu/address/testutil/CustomerUtil.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/OrderUtil.java
Labels: enhancement

#31 Improve find
  docs/UserGuide.md
  src/main/java/seedu/address/commons/util/ListUtil.java
  src/main/java/seedu/address/commons/util/PredicateUtil.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/AddCheeseCommand.java
  src/main/java/seedu/address/logic/commands/AddCustomerCommand.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AbstractId.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseCheeseTypePredicate.java
  src/main/java/seedu/address/model/customer/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerAddressPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerEmailPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerNamePredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerPhonePredicate.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/predicates/OrderCheeseTypePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderIdPredicate.java
  src/main/java/seedu/address/model/util/FilteredSortedList.java
  src/main/java/seedu/address/model/util/predicate/CompositeFieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/CompositeFieldPredicateBuilder.java
  src/main/java/seedu/address/model/util/predicate/FieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/SingleFieldPredicate.java
  src/test/java/seedu/address/commons/util/PredicateUtilTest.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCustomerCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/customer/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/util/predicate/CompositeFieldPredicateTest.java
  src/test/java/seedu/address/model/util/predicate/FieldPredicateTest.java
Labels: enhancement

#37 Update Delete Commands
  src/main/java/seedu/address/logic/commands/DeleteCheeseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/testutil/TypicalCheese.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalOrder.java
Labels: bug, enhancement

#38 Find Cheese Feature
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/commons/util/ListUtil.java
  src/main/java/seedu/address/commons/util/PredicateUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCheeseCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCustomerCommand.java
  src/main/java/seedu/address/logic/commands/DeleteOrderCommand.java
  src/main/java/seedu/address/logic/commands/FindCheeseCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCheeseCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/main/java/seedu/address/model/cheese/UniqueCheeseList.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseAssignmentStatusPredicate.java
  src/main/java/seedu/address/model/util/FilteredSortedList.java
  src/main/java/seedu/address/model/util/predicate/CompositeFieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/CompositeFieldPredicateBuilder.java
  src/main/java/seedu/address/model/util/predicate/FieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/SingleFieldPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedCheese.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/cards/CheeseCard.java
  src/main/resources/view/CheeseCard.fxml
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/commands/AddCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/AddCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/AddOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/FindCheeseCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/CheeseBuilder.java
Labels: bug, enhancement

#39 Model validation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCheeseCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/model/AbstractDate.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/main/java/seedu/address/model/cheese/UniqueCheeseList.java
  src/main/java/seedu/address/model/order/Order.java
  src/main/java/seedu/address/model/order/UniqueOrderList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedOrder.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/typicalAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
  src/test/java/seedu/address/logic/parser/AddOrderCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/cheese/CheeseTest.java
  src/test/java/seedu/address/model/order/OrderTest.java
  src/test/java/seedu/address/testutil/OrderBuilder.java
  src/test/java/seedu/address/testutil/TypicalCheese.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
  src/test/java/seedu/address/testutil/TypicalOrder.java
Labels: enhancement

#41 Find order feature
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindCheeseCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListOrdersCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCheeseCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/FindOrderCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseAssignmentStatusPredicate.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseCheeseTypePredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerAddressPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerEmailPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerNamePredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerPhonePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderCheeseTypePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderCompletionStatusPredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderNamePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderPhonePredicate.java
  src/main/java/seedu/address/model/util/predicate/SingleFieldPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/cards/OrderCard.java
  src/main/resources/view/OrderCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCheeseCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindOrderCommandParserTest.java
Labels: enhancement

#43 EditCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddOrderCommand.java
  src/main/java/seedu/address/logic/commands/EditCheeseCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditCustomerCommand.java
  src/main/java/seedu/address/logic/commands/EditOrderCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditCheeseCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCustomerCommandParser.java
  src/main/java/seedu/address/logic/parser/EditOrderCommandParser.java
  src/main/java/seedu/address/model/cheese/Cheese.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandStub.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCustomerDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/CustomerUtil.java
  src/test/java/seedu/address/testutil/EditCustomerDescriptorBuilder.java
Labels: enhancement

#45 Add summary for Find and List commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/ahquanz.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindCheeseCommand.java
  src/main/java/seedu/address/logic/commands/FindCustomerCommand.java
  src/main/java/seedu/address/logic/commands/FindOrderCommand.java
  src/main/java/seedu/address/logic/commands/ListCheesesCommand.java
  src/main/java/seedu/address/logic/commands/ListCustomersCommand.java
  src/main/java/seedu/address/logic/commands/ListOrdersCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseAssignmentStatusPredicate.java
  src/main/java/seedu/address/model/cheese/predicates/CheeseCheeseTypePredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerAddressPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerEmailPredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerNamePredicate.java
  src/main/java/seedu/address/model/customer/predicates/CustomerPhonePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderCheeseTypePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderCompletionStatusPredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderIdPredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderNamePredicate.java
  src/main/java/seedu/address/model/order/predicates/OrderPhonePredicate.java
  src/main/java/seedu/address/model/util/predicate/CompositeFieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/FieldPredicate.java
  src/main/java/seedu/address/model/util/predicate/SingleFieldPredicate.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/FindCheeseCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCustomerCommandTest.java
  src/test/java/seedu/address/logic/commands/FindOrderCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCheesesCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCustomersCommandTest.java
  src/test/java/seedu/address/logic/commands/ListOrdersCommandTest.java
  src/test/java/seedu/address/logic/commands/ModelStub.java
Labels: enhancement

#50 Update Developer Guide for UI Design and List Toggling Functionality
  docs/DeveloperGuide.md
  docs/diagrams/ListPanelTogglingSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiPanelsCardsClassDiagram.puml
  docs/images/ListPanelTogglingSequenceDiagram.png
  docs/images/UiClassDiagram.png
  docs/images/UiPanelsCardsClassDiagram.png
Labels: documentation

#49 Update developer guide for Logic and DeleteCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/DeleteCheeseSeqDiagram_CHIM.png
  docs/images/DeleteCustomerSeqDiagram_CHIM.png
  docs/images/LogicClassDiagram_CHIM.png
Labels: documentation

#51 Update find and storage documentation
  docs/DeveloperGuide.md
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/find/FindCheeseCommandSequenceDiagram.png
  docs/images/find/FindPredicateClassDiagram.png
  docs/index.md
  src/main/resources/view/MainWindow.fxml
Labels: documentation
